@startuml classes

class Physics {
    + bool processCollision(Ball&, Ball&)
    + bool processCollision(Ball&, const Vector2&)
    + bool processCollision(Ball&, const VerticalBorder&)
    + bool processCollision(Ball&, const HorizontalBorder&)
    + void processCollisions(Table&)
    + real timeUntilCollision(const Ball&, const Ball&, real)
    + real timeUntilCollision(const Ball&, const VerticalBorder&, real)
    + real timeUntilCollision(const Ball&, const HorizontalBorder&, real)
    + real timeWithoutCollisions(const Table&, real)
    + void simulate(Table&, real)
}

class Maths {
    + real length(const Vector2&)
    + real minQuadraticSolution(real, real, real, real)
}

class Vector2 {
    + Vector2(const sf::Vector2<real>&)
    + real dot(const Vector2&)
    + real squared()
    + real length()
}

class Ball {
    + real radius
    + Vector2 position
    + Vector2 velocity

    + Ball(const Vector2&, const Vector2&)
    + void move(real)
}

abstract Border {
    + Vector2 topLeft
    + Vector2 bottomRight

    + Border(const Vector2&, const Vector2&)
    + virtual ~Border()
    + real left()
    + real right()
    + real top()
    + real bottom()
}

class VerticalBorder {
    + real face
}

class HorizontalBorder {
    + real face
}

class Interface {
    - sf::RenderWindow window
    - void drawBall(const Ball&)
    - void drawBorder(const Border&)
    - void drawScene(const Table&)
    + Settings settings
    + Interface(Table&)
    + ~Interface()
    + void demonstrate(Table&)
    + Vector2 getStrikeVelocity()
    + void showGameResult()
    + void kill()
    + bool isAlive()
}

class Table {
    + real borderWidth
    + real h
    + real w
    + real frictionAcceleration
    + std::vector<Ball> balls
    + std::vector<std::shared_ptr<Border>> borders

    + Table();
    + void createBalls()
    + std::shared_ptr<Border> createBorder(const Vector2&, const Vector2&)
    + void createBorders()
    + bool ballsStopped()
    + void drawScene()
}

class Settings {
    + real scale
    + real fps

    + Settings()
    + void change()
}

enum GameState {
    + strike
    + simulation
    + end
}

class Game {
    Table table
    GameState state
    Interface interface

    Game()
    void mainLoop()
}

Game --o Table
Game --o GameState
Game --o Interface
Game --o Maths
Game --o Physics

Table --o Ball
Table --o VerticalBorder
Table --o HorizontalBorder

Interface --> Settings

Maths --> Vector2

class VerticalBorder implements Border
class HorizontalBorder implements Border

@enduml